[profile.default]
src = "src"
test = "test"
out = "out"
libs = []
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 5000
evm_version = "cancun"

[fuzz]
runs = 256

[invariant]
runs = 64
depth = 96
fail_on_revert = false
