import { createPublicClient, http, fallback, parseAbi, zeroAddress } from 'viem';
import { base } from 'viem/chains';
const client = createPublicClient({ chain: base, transport: fallback([http('https://base-rpc.publicnode.com'), http('https://mainnet.base.org')]) });
const USDC = '0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913', WETH='0x4200000000000000000000000000000000000006', NVDA='0xb20000000000000000000078ee7ce2fE4908108C';
const AERO_V2_FACTORY = '0x420DD381b31aEf6683db6B902084cB0FFECe40Da';
const AERO_CL_FACTORY = '0x5e7BB104d84c7CB9B682AaC2F3d509f5F406809A';
const AAVE_POOL = '0xA238Dd80C259a72e81d7e4664a9801593F98d1c5';
const AAVE_DATA = '0x0F43731EB8d45A581f4a36DD74F5f358bc90C73A';
const v2 = parseAbi(['function allPoolsLength() view returns (uint256)','function getPool(address tokenA, address tokenB, bool stable) view returns (address)']);
const cl = parseAbi(['function allPoolsLength() view returns (uint256)','function getPool(address tokenA, address tokenB, int24 tickSpacing) view returns (address)','function tickSpacings() view returns (int24[])']);
const pool = parseAbi(['function getReservesList() view returns (address[])']);
const dataAbi = parseAbi(['function getReserveConfigurationData(address asset) view returns (uint256 decimals, uint256 ltv, uint256 liquidationThreshold, uint256 liquidationBonus, uint256 reserveFactor, bool usageAsCollateralEnabled, bool borrowingEnabled, bool stableBorrowRateEnabled, bool isActive, bool isFrozen)','function getReserveData(address asset) view returns (uint256 unbacked, uint256 accruedToTreasuryScaled, uint256 totalAToken, uint256 totalStableDebt, uint256 totalVariableDebt, uint256 liquidityRate, uint256 variableBorrowRate, uint256 stableBorrowRate, uint256 averageStableBorrowRate, uint256 liquidityIndex, uint256 variableBorrowIndex, uint40 lastUpdateTimestamp)']);
const fmt = (v) => JSON.stringify(v, (k, x) => typeof x === 'bigint' ? x.toString() : x);
const t = async (label, fn) => { try { console.log('OK  ', label, '=>', fmt(await fn()).slice(0, 300)); } catch (e) { console.log('FAIL', label, '=>', (e.shortMessage||e.message).split('\n')[0]); } };
await t('aeroV2.allPoolsLength', () => client.readContract({ address: AERO_V2_FACTORY, abi: v2, functionName: 'allPoolsLength' }));
await t('aeroV2.getPool(USDC,NVDA,false)', () => client.readContract({ address: AERO_V2_FACTORY, abi: v2, functionName: 'getPool', args: [USDC, NVDA, false] }));
await t('aeroV2.getPool(WETH,NVDA,false)', () => client.readContract({ address: AERO_V2_FACTORY, abi: v2, functionName: 'getPool', args: [WETH, NVDA, false] }));
await t('aeroCL.allPoolsLength', () => client.readContract({ address: AERO_CL_FACTORY, abi: cl, functionName: 'allPoolsLength' }));
await t('aeroCL.tickSpacings', () => client.readContract({ address: AERO_CL_FACTORY, abi: cl, functionName: 'tickSpacings' }));
for (const ts of [1, 50, 100, 200, 2000]) await t(`aeroCL.getPool(USDC,NVDA,${ts})`, () => client.readContract({ address: AERO_CL_FACTORY, abi: cl, functionName: 'getPool', args: [USDC, NVDA, ts] }));
await t('aave.getReservesList', () => client.readContract({ address: AAVE_POOL, abi: pool, functionName: 'getReservesList' }));
await t('aaveData.getReserveConfigurationData(USDC)', () => client.readContract({ address: AAVE_DATA, abi: dataAbi, functionName: 'getReserveConfigurationData', args: [USDC] }));
await t('aaveData.getReserveData(USDC)', () => client.readContract({ address: AAVE_DATA, abi: dataAbi, functionName: 'getReserveData', args: [USDC] }));
